/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.casnw.home.hdata.io;

import java.util.HashMap;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.casnw.home.meta.DatatypeEnum;
import net.casnw.home.meta.TimescaleEnum;

/**
 *
 * @author minyufang
 */
public class TimeColumPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimeColumPanel
     */
    public TimeColumPanel(HashMap<String, Object[]> data) {
        initComponents();
        int colum = data.size() - 1;
        String[] headers = new String[colum];
        int i = 0;
        for (String key : data.keySet()) {
            if (i != 0) {
                headers[i-1] = key;             
            }
            i++;
        }
        Object[][] cellData = null;
        DefaultTableModel model = new DefaultTableModel(cellData, headers);
        jTable1.setModel(model);

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setCellSelectionEnabled(true);

        Object[] rowData = new Object[colum];
        for (int j = 0; j < colum; j++) {
            JComboBox cbox = new JComboBox();
            for (TimescaleEnum name : TimescaleEnum.values()) {
                cbox.addItem(name.toString());
            }
            TableCellEditor edt = new DefaultCellEditor(cbox);
            TableColumnModel colunmnModel = jTable1.getColumnModel();
            TableColumn tcol = colunmnModel.getColumn(j);
            tcol.setCellEditor(edt);
            rowData = null;
        }
        model.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
